// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnyZggnqZa3cKvK3gE8B1cg2_aNxMXgw',
    appId: '1:651549549527:web:31832363a5f247db876192',
    messagingSenderId: '651549549527',
    projectId: 'dealership-erp-sambaza-app',
    authDomain: 'dealership-erp-sambaza-app.firebaseapp.com',
    storageBucket: 'dealership-erp-sambaza-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFx1W8tdK9BTfW6636sWZRxTAee3DoLQg',
    appId: '1:651549549527:android:f3aaff51b127b01c876192',
    messagingSenderId: '651549549527',
    projectId: 'dealership-erp-sambaza-app',
    storageBucket: 'dealership-erp-sambaza-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1NAb3pAnyiUS8VlFslm8CKnQu54nUsU',
    appId: '1:651549549527:ios:a67529b095756071876192',
    messagingSenderId: '651549549527',
    projectId: 'dealership-erp-sambaza-app',
    storageBucket: 'dealership-erp-sambaza-app.firebasestorage.app',
    iosBundleId: 'com.example.dealershipErpSambazaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1NAb3pAnyiUS8VlFslm8CKnQu54nUsU',
    appId: '1:651549549527:ios:a67529b095756071876192',
    messagingSenderId: '651549549527',
    projectId: 'dealership-erp-sambaza-app',
    storageBucket: 'dealership-erp-sambaza-app.firebasestorage.app',
    iosBundleId: 'com.example.dealershipErpSambazaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDnyZggnqZa3cKvK3gE8B1cg2_aNxMXgw',
    appId: '1:651549549527:web:064867406c81d4db876192',
    messagingSenderId: '651549549527',
    projectId: 'dealership-erp-sambaza-app',
    authDomain: 'dealership-erp-sambaza-app.firebaseapp.com',
    storageBucket: 'dealership-erp-sambaza-app.firebasestorage.app',
  );
}
